In [29]:
%matplotlib inline
import numpy as np
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
from IPython.display import clear_output

In [30]:
# dimension of input
dims = 80

signal_length = 100
signal_repeats = 3
predict_ahead = 1
noise_strength = 0.03
total_series_length = signal_length * signal_repeats

In [31]:
def generateData(dims, signal_length, predict_ahead, 
                 signal_repeats, batch_size, noise_strength):
    total_series_length = signal_length * signal_repeats
    time = np.linspace(
        0, np.pi*2*signal_repeats, 
        total_series_length * dims + predict_ahead * dims, dtype=np.float32
    )
    time = time.reshape((1, -1, dims))  
    
    # include shift for batches
    time = np.repeat(time, batch_size, 0)
    time += np.random.random(batch_size)[:, None, None] * 10
    y = np.sin(time)
    input_ = y[:, :total_series_length, :].copy()
    if noise_strength > 0:
        input_ += np.random.normal(size=(input_.shape)) * noise_strength # add some noise to the input
    target = y[:, predict_ahead:, :]
    return torch.tensor(input_) , torch.tensor(target)

In [32]:
# first, define our model and initialize the learnable weights and biases (parameters):
class LSTM(nn.Module):
    def __init__(self, dims, hidden_dims,
                 learn_h0=False, learn_c0=False,
                 activation_h=nn.Tanh,
                 activation_o=nn.Sigmoid, activation_f=nn.Tanh, 
                 activation_i=nn.Sigmoid, activation_j=nn.Sigmoid, 
                 rnn_mode=True):
        super().__init__()
        # it is fine to hard code these 
        self.activation_h = activation_h()
        self.activation_o = activation_o()
        self.activation_f = activation_f()
        self.activation_i = activation_i()
        self.activation_j = activation_j()
        
        # parameters of the (recurrent) hidden layer
        self.W_o = nn.Parameter(torch.randn(dims, hidden_dims) * .1)
        self.b_o = nn.Parameter(torch.zeros(1, hidden_dims))
        self.W_f = nn.Parameter(torch.randn(dims, hidden_dims) * .1)
        self.b_f = nn.Parameter(torch.zeros(1, hidden_dims))
        self.W_i = nn.Parameter(torch.randn(dims, hidden_dims) * .1)
        self.b_i = nn.Parameter(torch.zeros(1, hidden_dims))
        self.W_j = nn.Parameter(torch.randn(dims, hidden_dims) * .1)
        self.b_j = nn.Parameter(torch.zeros(1, hidden_dims))
        
        
        self.U_o = nn.Parameter(
            torch.randn(hidden_dims, hidden_dims) * .1
        )
        self.U_f = nn.Parameter(
            torch.randn(hidden_dims, hidden_dims) * .1
        )
        self.U_i = nn.Parameter(
            torch.randn(hidden_dims, hidden_dims) * .1
        )
        self.U_j = nn.Parameter(
            torch.randn(hidden_dims, hidden_dims) * .1
        )
        
        if not rnn_mode:
            self.U_o.zero_(); self.U_f.zero_(); self.U_i.zero_(); self.U_j.zero_()
            self.U_o.requires_grad = False
            self.U_f.requires_grad = False
            self.U_i.requires_grad = False
            self.U_j.requires_grad = False

        # initial hidden state
        self.h_0 = nn.Parameter(
            torch.zeros(1, hidden_dims),
            requires_grad=learn_h0 # only train this if enabled
        )        
        
        # initial cell state
        self.c_0 = nn.Parameter(
            torch.zeros(1, hidden_dims),
            requires_grad=learn_c0 # only train this if enabled
        )
        
        # output layer (fully connected)
        self.W_y = nn.Parameter(torch.randn(hidden_dims, dims) * .1)
        self.b_y = nn.Parameter(torch.zeros(1, dims))
                
    def step(self, x_t, h, c):
        #  forward pass for a single time step
        # hint: a more clever implementation could combine all these and select the different parts later
        j = self.activation_j(
            torch.matmul(x_t, self.W_j) + torch.matmul(h, self.U_j) + self.b_j
        )
        i = self.activation_i(
            torch.matmul(x_t, self.W_i) + torch.matmul(h, self.U_i) + self.b_i
        )
        f = self.activation_f(
            torch.matmul(x_t, self.W_f) + torch.matmul(h, self.U_f) + self.b_f
        )        
        o = self.activation_o(
            torch.matmul(x_t, self.W_o) + torch.matmul(h, self.U_o) + self.b_o
        )
        
        
        c = f * c + i * j
        
        h = o * self.activation_h(c)

        return h, c # returning new hidden and cell state

    def iterate_series(self, x, h, c):
        # apply rnn to each time step and give an output (many-to-many task)
        batch_size, n_steps, dimensions = x.shape
        
        # can use cell states list here but only the last cell is required
        hidden_states = []
        # iterate over time axis (1)
        for t in range(n_steps):
            # give previous hidden state and input from the current time step
            h, c = self.step(x[:, t], h, c)
            hidden_states.append(h)
        hidden_states = torch.stack(hidden_states, 1)
        
        # fully connected output
        y_hat = hidden_states.reshape(batch_size * n_steps, -1) # flatten steps and batch size (bs * )
        y_hat = torch.matmul(y_hat, self.W_y) + self.b_y
        y_hat = y_hat.reshape(batch_size, n_steps, -1) # regains structure
        return y_hat, hidden_states[:, -1], c
    
    def forward(self, x, h, c):
        # x: b, t, d
        batch_size = x.shape[0] 
        if h is None:
            h = self.h_0.repeat_interleave(batch_size, 0)
        if c is None:
            c = self.c_0.repeat_interleave(batch_size, 0)
        y_hat, h, c = self.iterate_series(x, h, c)
        return y_hat, h, c
    
    def auto_regression(self, x_0, h, c, steps):
        # one-to-many task (steps = \delta')
        x_prev = x_0
        y_hat = []
        # iterate over time axis (1)
        for t in range(steps):
            # give previous hidden state and input from the current time step
            h, c = self.step(x_prev, h, c)
            # here we need to apply the output layer on each step individually
            x_prev = torch.matmul(h, self.W_y) + self.b_y
            
            y_hat.append(x_prev)
        y_hat = torch.stack(y_hat, 1)
        return y_hat, h, c
    
    def many_to_one(self, x, h, c):
        # not required
        # returns the last prediction and the hidden state
        y_hat, h, c = self(x, h, c)
        return y_hat[:, -1], h, c # only return the last prediction
        
    def many_to_many_async(self, x, h, c, steps):
        # not required
        # combines many-to-one and one-to-many
        x_0, h, c = self.many_to_one(x, h, c)
        return self.auto_regression(x_0, h, c, steps)

In [33]:
# use the hidden state (True) by activating learning for U_h
rnn_mode = True
# learn a better initial hidden state representation (True) than zero init
learn_h0 = True

# number of weight update iterations
n_iterations = 25 #250

# number of neurons m in the hidden layer
num_neurons = 256
batch_size  = 1024 #should be 1024
lr = 0.01

device = "cuda"

In [34]:
rnn = LSTM(
    dims, num_neurons, 
    learn_h0=learn_h0, 
    rnn_mode=rnn_mode
)
rnn.to(device)

# standard optimizer SGD or AdaGrad would also work
optimizer = torch.optim.Adam(rnn.parameters(), lr=lr)

In [35]:
rnn.train()
iteration = 0
# how often we plot the prediction
log_iter = 10
iter_loss = []

# train for a set number of iterations
for iteration in range(n_iterations):

    # generates a long time series / normally loaded from dataset (e.g. stocks, weather)
    x, y = generateData(
        dims, signal_length, predict_ahead, signal_repeats, batch_size, noise_strength
    )

    x, y = x.to(device), y.to(device)
    h = c = None
    # reset gradients
    optimizer.zero_grad()
    
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)

#    t0 = time.time()
    start.record()

    # get predictions (forward pass)
    y_hat, h, c = rnn(x, h, c)
           
    # calculate mean squared error
    loss = torch.mean((y_hat - y)**2)        
    # backprop
    loss.backward()

    end.record()
#    torch.cuda.current_stream().synchronize()
#    t1 = time.time()
#    print(t1-t0)

    # Waits for everything to finish running
    torch.cuda.synchronize()

    print(start.elapsed_time(end))

    print(rnn.W_o.grad)
    # finally we are adapting the weights with the saved gradient information
    optimizer.step()


    # log loss
#    iter_loss.append(loss.item())
    
    # plot model predictions during training
#    if iteration % log_iter == 0:
#        replot(x[0].cpu(), y_hat[0].detach().cpu(), 
#               y[0].cpu(), iteration + 1, iter_loss)

267.7424011230469
tensor([[ 0.0014, -0.0005, -0.0016,  ...,  0.0018, -0.0004,  0.0005],
        [ 0.0014, -0.0005, -0.0016,  ...,  0.0018, -0.0004,  0.0005],
        [ 0.0014, -0.0005, -0.0016,  ...,  0.0018, -0.0004,  0.0005],
        ...,
        [ 0.0014, -0.0005, -0.0016,  ...,  0.0018, -0.0004,  0.0005],
        [ 0.0014, -0.0005, -0.0016,  ...,  0.0018, -0.0004,  0.0005],
        [ 0.0014, -0.0005, -0.0016,  ...,  0.0018, -0.0004,  0.0005]],
       device='cuda:0')
231.70684814453125
tensor([[-3.4384e-04,  3.0527e-04,  1.2909e-04,  ...,  4.5885e-04,
          2.0903e-04,  1.7892e-05],
        [-3.4387e-04,  3.0510e-04,  1.2920e-04,  ...,  4.5886e-04,
          2.0911e-04,  1.7983e-05],
        [-3.4392e-04,  3.0503e-04,  1.2920e-04,  ...,  4.5877e-04,
          2.0904e-04,  1.8006e-05],
        ...,
        [-3.4485e-04,  2.9816e-04,  1.3440e-04,  ...,  4.5764e-04,
          2.1051e-04,  2.1856e-05],
        [-3.4491e-04,  2.9799e-04,  1.3447e-04,  ...,  4.5754e-04,
          2.1

217.96560668945312
tensor([[ 1.1078e-06, -4.6604e-06,  3.7407e-07,  ...,  2.0958e-05,
         -6.1355e-07, -1.3685e-04],
        [ 1.1044e-06, -4.6465e-06,  3.7426e-07,  ...,  2.0969e-05,
         -6.1381e-07, -1.3670e-04],
        [ 1.0947e-06, -4.6471e-06,  3.7191e-07,  ...,  2.0990e-05,
         -6.1412e-07, -1.3671e-04],
        ...,
        [ 7.1635e-07, -4.7751e-06,  5.1516e-07,  ...,  2.0429e-05,
         -5.5896e-07, -1.3359e-04],
        [ 7.0866e-07, -4.7755e-06,  5.2146e-07,  ...,  2.0397e-05,
         -5.5451e-07, -1.3353e-04],
        [ 7.0681e-07, -4.7794e-06,  5.2241e-07,  ...,  2.0423e-05,
         -5.5481e-07, -1.3354e-04]], device='cuda:0')
217.97120666503906
tensor([[-8.8126e-07,  4.2610e-06,  5.2992e-07,  ..., -2.4921e-05,
         -8.8927e-07, -1.2714e-04],
        [-8.8756e-07,  4.2625e-06,  5.3157e-07,  ..., -2.4916e-05,
         -8.8983e-07, -1.2695e-04],
        [-8.9275e-07,  4.2646e-06,  5.2891e-07,  ..., -2.4884e-05,
         -8.9024e-07, -1.2698e-04],
    